/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/FullScreen/Clock.vue')['default']
    DigitalClock: typeof import('./src/components/FullScreen/DigitalClock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ReactangleOutline: typeof import('./src/components/ReactangleOutline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rss: typeof import('./src/components/rss/Rss.vue')['default']
    SquareOutline: typeof import('./src/components/SquareOutline.vue')['default']
    Time: typeof import('./src/components/time/Time.vue')['default']
    Weather: typeof import('./src/components/weather/weather.vue')['default']
  }
}
